import React from 'react';
import TextField from '@material-ui/core/TextField';
import FormControlLabel from '@material-ui/core/FormControlLabel';
import Checkbox from '@material-ui/core/Checkbox';
import { makeStyles } from '@material-ui/core/styles';


const useStyles = makeStyles(theme => ({
  root: {
    display: 'flex',
    flexWrap: 'wrap',
  },
  terms: {
      overflow: 'auto',
      width: '75%',
      height: '400px',
  }
}));


export default function() {

    const classes = useStyles();

    const [accepted, setAccepted] = React.useState(false);
    
      const handleChange = event => {
        setAccepted(event.target.checked );
      };

    return (
        <div>
            <h1>Please review our terms &amp; conditions and privacy policy</h1>
            
            <div className={classes.terms}>
					<h3>Please Note: UPDATED EFFECTIVE: June 6, 2016</h3>
<p>The following are the terms of use (“Terms”) that govern your use of the Broker Genius Site, related websites, applications, mobile platforms, services, tools, modules, integrated application sites and remote services, servers, and services residing on servers owned and/or operated by third parties (collectively, the “Site, Services or Apps”). Our Privacy Policy, Purchase Policy, and any other policies, rules or guidelines that may be applicable to particular offers or features on the Site, Services or Apps are also incorporated into these Terms. By visiting or using the Site, Services or Apps or using Broker Genius Apps, you expressly agree to these Terms, as updated from time to time.</p>
<p>We are not responsible for the accuracy of any information displayed in our Apps, Services or Sites, for any or untimely, latent or missed transaction. We are not responsible for user account data and are not responsible or liable for accidental or intention data loss through the use of our Apps, Services or Sites.</p>
<p>We may make changes to these Terms at any time. Any changes we make will be effective immediately when we post a revised version of these Terms on the Site or Apps. The “Last Updated” date above will tell you when these Terms were last revised. By continuing to use this Site or Apps after that date, you agree to the changes.</p>
<p>The Site or Apps are not intended for children under the age of 13 and no person under the age of 13 may use the Site or Apps. We strongly encourage all parents and guardians to monitor the Internet use by their children. If you use the Site or Apps, you affirm you are at least 13 years old.</p>
<h2>Updates to Terms</h2>
<p>We will notify you either through a direct communication, social medial channels or other mechanisms when our terms of use and policy provisions change.</p>
<h3>Account Registration</h3>
<p>You will be required to register for an account to use certain features of the Site or Apps, such as but not limited to, integrating with point of sale systems, purchasing a tickets, and listing tickets on ticket exchange networks. Your account username may not include the name of another person with the intent to impersonate that person, or be offensive, vulgar or obscene. Your account username and password are personal to you. You will be responsible for the confidentiality and use of your username and password, and for all activities (including commercial transactions) that are conducted through your account. You may not transfer or sell access to your account. We will not be liable for any harm related to disclosure of your username or password or the use by anyone else of your username or password. You may not use another user’s account without that user’s permission. You will immediately notify us in writing if you discover any unauthorized use of your account or other account-related security breach. We may require you to change your username and/or password if we believe your account is no longer secure or if we receive a complaint that your username violates someone else’s rights. You will have no ownership in your account or your username. We may refuse registration, cancel an account or deny access to the Site or Apps for any reason.</p>
<h3>Third Party Access and Authorization</h3>
<p>Broker Genius provides custom software solutions in order to optimize the ticket selling process. In order to provide the most up-to-date information to you, we ask for and you provide your password and user name to any ticket exchange account service that you wish to integrate with your Broker Genius service.</p>
<p>Furthermore, based on your use of the site, service and apps, Broker Genius may create and maintain, for your sole benefit, an access or developer key to a 3rd party API or developer program.&nbsp;By agreeing to the terms of use herein, you grant Broker Genius the right to obtain and implement a software strategy that includes creating a developer instance or account on your behalf for your sole benefit, based on 3rd party account information, and implementing or operating a software solution for your benefit.You further agree to be bound the restrictions of any and all 3rd party API or developer program terms of use agreements. Stubhub’s API license agreement can be found&nbsp;<a href="https://developer.stubhub.com/store/site/pages/terms.jag" target="_blank" rel="noopener">here</a>.</p>
<h2>Code of Conduct</h2>
<h3>You agree that you will comply with all applicable laws, rules and regulations, and that you will not:</h3>
<h5></h5>
<ul>
<li>Restrict or inhibit any other person from using the Site or Apps;</li>
<li>Use the Site or Apps for any unlawful purpose;</li>
<li>Express or imply that any statements you make are endorsed by us, without our prior written consent;</li>
<li>Impersonate any person or entity, whether actual or fictitious, including any employee or representative of our company;</li>
<li>Submit (a) any content or information that is unlawful, fraudulent, libelous, defamatory, or otherwise objectionable, or infringes our or any third party’s intellectual property or other rights; (b) any non-public information about companies without authorization; or (c) any advertisements, solicitations, chain letters, pyramid schemes, surveys, contests, investment opportunities or other unsolicited commercial communication;</li>
<li>Submit, or provide links to, any postings containing material that could be considered harmful, obscene, pornographic, sexually explicit, indecent, lewd, violent, abusive, profane, insulting, threatening, harassing, hateful or otherwise objectionable, includes the image or likeness of individuals under 18 years of age, encourages or otherwise depicts or glamorizes drug use (including alcohol and cigarettes), characterizes violence as acceptable, glamorous or desirable, or contains any personal contact information or other personal information identifying any third party;</li>
<li>Submit, or provide links to, any postings containing material that harasses, victimizes, degrades, or intimidates an individual or group of individuals on the basis of religion, race, ethnicity, sexual orientation, gender, age, or disability;</li>
<li>Engage in spamming or flooding;</li>
<li>Harvest or collect information about Site or Apps users;</li>
<li>Use or derive data to determine Broker Genius functionality, user information, aggregate statistics on Broker Genius’s performance, or the performance of third party data integration partners.</li>
<li>Circumvent restrictions placed on the types and form of data available through Broker Genius or attempt to subvert or compromise Tinoxomy’s ability to provide users with valid and accurate information.</li>
<li>Change, use or manipulate data in any way that is misleading to any user, customer, end user, or recipient of information.</li>
<li>Violate the terms of use for</li>
</ul>
<h3>Ownership of Data, Content and Grant of Conditional License</h3>
<p>The Site or Apps and all data, text, designs, pages, print screens, images, artwork, photographs, audio and video clips, and HTML code, source code, or software that resides or is viewable, submitted or otherwise discoverable on the Site or Apps (collectively, the “Content”) is owned by us or our licensors. We own a copyright in the Site or Apps and Content. We may change the Content and features of the Site or Apps at any time.</p>
<p>We grant you a limited, conditional, no-cost, non-exclusive, non-transferable, non-sub-licensable license to view or use this Site or Apps and its Content as permitted by these Terms, as a condition precedent, you agree that you will not:</p>
<ul>
<li>Submit any software or other materials that contain any viruses, worms, Trojan horses, defects, date bombs, time bombs or other items of a destructive nature;</li>
<li>Manipulate identifiers, including by forging headers, in order to disguise the origin of any actions conduct with or through the site or Apps;</li>
<li>Link to any portion of the Site or Apps other than the URL assigned to the home page of our Site or a URL for user storage located within the Apps;</li>
<li>“Frame” or “mirror” any part of the Site or Apps;</li>
<li>Modify, adapt, sub-license, translate, sell, reverse engineer, decompile or disassemble any portion of the Site or Apps or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Site or Apps;</li>
<li>Remove any copyright, trademark or other proprietary rights notices contained on/in the Site or Apps;</li>
<li>Use any robot, spider, offline reader, Site, Apps, search/retrieval application or other manual or automatic device, tool, or process to retrieve, index, data mine or in any way reproduce or circumvent the navigational structure or presentation of the Site or Apps or its contents, including with respect to any CAPTCHA displayed on the Site or Apps. Operators of public search engines may use spiders to copy materials from the Site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials. We may revoke this exception at any time;</li>
<li>Take any action that imposes or may impose (in our sole discretion) an unreasonable or disproportionately large load on our infrastructure;</li>
<li>Access, reload or refresh transactional event or ticketing pages, or make any other request to transactional servers, more than once during any three-second interval;</li>
<li>Reproduce, modify, display, publicly perform, distribute or create derivative works of the Site or Apps or the Content;</li>
</ul>
<p>Use the Site or Apps or the Content in an attempt to, or in conjunction with, any device, program or service designed to circumvent any technological measure that effectively controls access to, or the rights in, the Site or Apps and/or Content in any way including, without limitation, by manual or automatic device or process, for any purpose.</p>
<p>This license is expressly conditioned on your preexisting agreement to comply with, and your actual compliance with, each of the provisions described in this Ownership of Content and Grant of Conditional License section. This license exists only so long as you strictly comply with each of the provisions described in this section. Any use of the Site, Apps or Content by you or anyone acting on your behalf that does not strictly comply with each and every provision in this section exceeds the scope of the license granted to you herein, constitutes unauthorized reproduction, display, or creation of unauthorized derivative versions of the Site, Apps and Content, and infringes our copyrights and other rights in the Site or Apps and Content. You will not acquire any ownership rights by using the Site or Apps or the Content.</p>
<p>The registered and unregistered trademarks, logos and service marks displayed on the Site or Apps are owned by us or our licensors. You may not use our trademarks, logos and service marks in any way without our prior written permission. You may inquire about obtaining permission by writing:</p>
<p>Broker Genius, Inc.<br/>
181 South Franklin Ave.<br/>
Valley Stream, NY 11581<br/>
<a href="https://support@brokergenius.com/" target="_blank" rel="noopener">support@brokergenius.com</a></p>
<h3>Transactions</h3>
<p>You will pay all charges incurred by you or any users of your account and credit card (or other applicable payment mechanism) at the price(s) in effect when such charges are incurred, including any applicable taxes. You will pay any applicable taxes for any sale or transaction for which taxes may be withheld or otherwise be due to any government or body. You may only use credit or debit cards, gift cards or vouchers that belong to you or to people who expressly authorize you to use such payment methods. You may not attempt to conceal your identity by using multiple Internet Protocol addresses or email addresses to conduct transactions on the Site or Apps. You will not hold us liable if you do not comply with laws related to your transactions. We may provide law enforcement with information you provide to us related to your transactions to assist in any investigation or prosecution of you. If we are unable to verify or authenticate you provide during any registration, ordering, purchase, ticket posting, sale, authentication, delivery, payment or remittance process, or any other process, we may prohibit you from using the Site or Apps.</p>
<h3>User Content and Data</h3>
<p>By agreeing to the terms of use herein, you grant Broker Genius the right to access, retrieve, and/or exchange information, including but not limited to historical, transactional, or usage or other data from or with any point of sale systems, ticket network, or other 3rd party software platforms that you have authorized for integration with the Site or Apps (“User Data”). You own all rights to your User Data. You grant us a worldwide, non-exclusive, transferable, sublicenseable, royalty-free right and license to use, reproduce, modify, create derivative works of, distribute, publicly perform, display, archive and commercialize your User Data, in our sole discretion without any compensation or acknowledgment to you or anyone else. This license will not affect your ownership in your User Data, including the right to grant additional licenses to your User Data, except if it conflicts with these Terms. You will not make or authorize any claim against us that our use of your User Data infringes any of your rights.</p>
<p>We may host reviews, message boards, blog feeds, social media feeds and other forums found on the Site or Apps (collectively, “Forums”), and you may be able to submit suggestions, reviews, concepts, audio and video recordings, photographs, artwork or other materials to the Forums or other areas of the Site or Apps (“User Content”).</p>
<p>By submitting User Content, you certify that you are at least 18 years old, or you are at least 13 years old and have obtained your parent’s or legal guardian’s express consent to submit User Content.</p>
<p>You own all rights to your User Content. If you submit User Content to the Site or Apps, you grant us a worldwide, non-exclusive, transferable, sublicenseable, royalty-free right and license to use, reproduce, modify, create derivative works of, distribute, publicly perform, display, archive and commercialize your User Content, in our sole discretion, in all formats and in all media channels now known or hereinafter discovered, without any compensation or acknowledgment to you or anyone else. This license will not affect your ownership in your User Content, including the right to grant additional licenses to your User Content, except if it conflicts with these Terms. We are not obligated to post, display or otherwise use any User Content, or to attribute your User Content to you. You will not make or authorize any claim against us that our use of your User Content infringes any of your rights.</p>
<p>Statements, opinions and reviews posted by participants in a Forum may be inaccurate, offensive, obscene, threatening or harassing. We do not endorse and are not responsible for these postings. We will not be liable for any loss or harm caused by the posting or your reliance on information obtained through the postings</p>
<p>You will be responsible for your User Content and the consequences of posting it. By submitting User Content, you represent to us that (i) you own, or have the necessary permission to submit the User Content and to grant the licenses to us under this section, and (ii) you have the written permission of every identifiable person in the User Content to use that person’s name and likeness in the manner contemplated by the Site or Apps and these Terms or, if the person is a minor, the written permission of the minor’s parent or legal guardian</p>
<p>We will have the right (but not the obligation) to monitor the Site or Apps, the Forums and the User Content, and to disclose any User Content and the circumstances surrounding its submission in order to operate the Site or Apps properly, or to protect ourselves, our sponsors and our users, or to comply with legal obligations or governmental requests.</p>
<p>If we are notified that your User Content does not comply with these Terms, we may investigate the allegation and may decide to remove your User Content and cancel your account.</p>
<h3>Claims of Copyright Infringement On The Site or Apps</h3>
<p>Under the Digital Millennium Copyright Act of 1998 (the “DMCA”) if you believe in good faith that any content on the Site or Apps infringes your copyright, you may send us a notice requesting that the content be removed. The notice must include: (a) your (or your agent’s) physical or electronic signature; (b) identification of the copyrighted work on our Site or Apps that is claimed to have been infringed (or a representative list if multiple copyrighted works are included in one notification); (c) identification of the content that is claimed to be infringing or the subject of infringing activity, including information reasonably sufficient to allow us to locate the content on the Site or Apps; (d) your name, address, telephone number and email address (if available); (e) a statement that you have a good faith belief that use of the content in the manner complained of is not authorized by you or your agent or the law; and (f) a statement that the information in the notification is accurate and, under penalty of perjury, that you or your agent is authorized to act on behalf of the copyright owner. If you believe in good faith that a notice of copyright infringement has been wrongly filed against you, you may send us a counter-notice. You may read more information about the DMCA at&nbsp;<a href="http://www.loc.gov/copyright">http://www.loc.gov/copyright.</a></p>
<h2>Notices and counter-notices should be sent to:</h2>
<p>Copyright Officer<br/>
Broker Genius, Inc<br/>
<a href="https://support@brokergenius.com/" target="_blank" rel="noopener">support@brokergenius.com</a></p>
<p>There can be penalties for false claims under the DMCA. We suggest that you consult your legal advisor before filing a notice or counter-notice.</p>
<h3>Links</h3>
<p>The Site or Apps contains links and access to other Websites or Apps that may not be owned or operated by us. The fact that we may link to those website or Apps does not indicate any approval or endorsement of those websites or Apps. We have no control over those websites or Apps. We are not responsible for the content of those website or Apps, or the privacy practices of those website or Apps. We strongly encourage you to become familiar with the terms of use and practices of any linked website or Apps. Your use of other website or Apps is at your own risk and is subject to the terms of those website or Apps. It is up to you to take precautions to ensure that whatever links you select or software you download (whether from the Site or Apps or other Site or Apps) is free of viruses, worms, Trojan horses, defects, date bombs, time bombs and other items of a destructive nature.</p>
<h3>Parental Controls</h3>
<p>We cannot prohibit minors from visiting our Site or Apps, and must rely on parents and guardians to decide what transactions to enter into. There are parental control protections (such as computer hardware, software or filtering services) available that may assist you in limiting access to material that is harmful to minors. You can find information about parental controls at http://onguardonline.gov and http://kids.getnetwise.org. We do not endorse the products or services listed at these website or Apps.</p>
<h3>Access from Outside the United States</h3>
<p>The Site or Apps is directed to people residing in the United States. We do not represent that Content available on or through the Site or Apps is appropriate or available in other locations. We may limit the availability of the Site or Apps or any service or product described on the Site or Apps to any person or geographic area at any time. If you choose to access the Site or Apps from outside the United States, you do so at your own risk.</p>
<h3>Mobile Messaging</h3>
<p>We may offer browsing and mobile messaging services which may include alerts. Mobile messaging may be provided by a 3rd party.</p>
<p>Message and data rates may apply, according to your rate plan provided by your wireless carrier. We will not be responsible for any text messaging or other wireless charges incurred by you or by a person who has access to your wireless device or telephone number. You may not receive our alerts if your carrier does not permit text alerts. Your carrier may not allow you to use pre-paid phones or calling plans to receive alerts. We may send you a bounce back message for every message you send to us. Service may not be compatible with all wireless carriers or devices. You may opt out of any alerts as specifically provided by any 3rd party provider.</p>
<p>We are not responsible for the accuracy of any information displayed in our mobile messaging, for any mis-delivery or untimely delivery of any mobile messaging, or your deletion or failure to store any mobile messaging from us.</p>
<h3>Mobile Device Application</h3>
<p>If you install or use our mobile application, software and services, including any accompanying documentation (collectively, ” Mobile App”), we grant you a limited right to install and use the App on a single authorized device located in the United States and its territories or in another country where we may offer the Mobile App. You may use the Mobile App for your personal, non-commercial and entertainment purposes only. You agree to also comply with any App Store Terms of Service. We do not grant you any rights to any related documentation, support, upgrades, maintenance or other enhancements to the Mobile App. We will not provide you with any device, internet access or wireless connection to use the Mobile App. We are not responsible for any interaction between you and another App user, or information you transmit through the App (including your location).</p>
<h3>Violation of these Terms</h3>
<p>We may investigate any violation of these Terms, including unauthorized use of the Site or Apps. We may take legal action that we feel is appropriate. You agree that monetary damages may not provide us a sufficient remedy and that we may pursue injunctive or other relief for your violation of these Terms. If we determine that you have violated these Terms or the law, or for any other reason or for no reason, we may cancel your account, delete all your User Content and prevent you from accessing the Site or Apps at any time without notice to you. If that happens, you may no longer use the Site or Apps or any Content. You will still be bound by your obligations under these Terms. You agree that we will not be liable to you or any third party for termination of your access to the Site or Apps or to your account or any related information, and we will not be required to make the Site or Apps or your account or any related information available to you. We may refuse to honor pending and future transactions made from all accounts we believe may be associated with you.</p>
<p>You agree that your abusive use of the Site or Apps may cause damage and harm to us, including impaired goodwill, lost sales and increased expenses. You also agree that monetary damages for your abusive use of the Site or Apps are difficult to determine and that you, and those acting with you, will be jointly and severally liable for liquidated damages.</p>
<h3>Disclaimer of Warranties</h3>
<p>WE PROVIDE THE SITE OR APPS AND THE CONTENT TO YOU “AS IS” AND “AS AVAILABLE”. WE TRY TO KEEP THE SITE OR APPS UP, BUG-FREE AND SAFE, BUT YOU USE IT AT YOUR OWN RISK. TO THE FULLEST EXTENT PERMISSIBLE BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTY OF TITLE, NON-INFRINGEMENT, ACCURACY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING OR COURSE OF PERFORMANCE OR USAGE OF TRADE. WE DO NOT GUARANTEE THAT THE SITE OR APPS WILL ALWAYS BE SAFE, SECURE OR ERROR-FREE OR THAT THE SITE OR APPS WILL ALWAYS FUNCTION WITHOUT DISRUPTIONS, DELAYS OR IMPERFECTIONS. WE ARE NOT RESPONSIBLE FOR THE ACTIONS OR INFORMATION OF THIRD PARTIES, AND YOU RELEASE US FROM ANY CLAIMS AND DAMAGES, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH ANY CLAIM YOU HAVE AGAINST ANY SUCH THIRD PARTIES. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO SOME OF THESE EXCLUSIONS MAY NOT APPLY TO YOU. IF YOU ARE A CALIFORNIA RESIDENT, YOU WAIVE CALIFORNIA CIVIL CODE §1542, WHICH SAYS: A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.</p>
<h3>Limitation of Liability</h3>
<p>IN NO EVENT WILL WE OR OUR SUPPLIERS, ADVERTISERS AND SPONSORS, BE RESPONSIBLE OR LIABLE TO YOU OR ANYONE ELSE FOR, AND YOU HEREBY KNOWINGLY AND EXPRESSLY WAIVE ALL RIGHTS TO SEEK, DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES OF ANY TYPE OTHER THAN OUT OF POCKET EXPENSES, AND ANY RIGHTS TO HAVE DAMAGES MULTIPLIED OR OTHERWISE INCREASED, ARISING OUT OF OR IN CONNECTION WITH THE SITE OR APPS, THE USER CONTENT AND DATA, OR ANY PRODUCT OR SERVICE PURCHASED THROUGH THE SITE OR APPS, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND REGARDLESS OF WHETHER THE CLAIM IS BASED UPON ANY CONTRACT, TORT, OR OTHER LEGAL OR EQUITABLE THEORY. WITHOUT LIMITING THE FOREGOING, YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT WE WILL HAVE NO LIABILITY OR RESPONSIBILITY WHATSOEVER FOR:<br/>
(a) ANY FAILURE OF ANOTHER USER OF THE SITE OR APPS TO CONFORM TO THE CODES OF CONDUCT,<br/>
(b) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, WHETHER ARISING IN CONTRACT OR IN TORT, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SITE OR APPS,<br/>
(c) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN,<br/>
(d) ANY BUGS, VIRUSES, WORMS, TROJAN HORSES, DEFECTS, DATE BOMBS, TIME BOMBS OR OTHER ITEMS OF A DESTRUCTIVE NATURE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SITE OR APPS,<br/>
(e) ANY ERRORS, MISTAKES, INACCURACIES OR OMISSIONS IN ANY CONTENT, OR<br/>
(f) ANY LOST, STOLEN OR DAMAGED TICKETS or TRANSACTIONS, OR THE FAILURE OF A VENUE TO HONOR A TICKET. YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH THE SITE OR APPS IS TO STOP USING THE SITE OR APPS. THE LIMITATIONS IN THIS SECTION WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. THE ALLOCATION OF RISK BETWEEN US IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN US. OUR AGGREGATE LIABILITY ARISING OUT OF THESE TERMS OR THE USE OF THE SITE OR APPS WILL NOT EXCEED THE GREATER OF ONE HUNDRED DOLLARS ($100) OR THE AMOUNT YOU HAVE PAID US IN THE PAST TWELVE MONTHS. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF DAMAGES, SO THESE MAY NOT APPLY TO YOU. IN SUCH CASES, OUR LIABILITY WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW. IN NO EVENT WILL ATTORNEYS’ FEES BE AWARDED OR RECOVERABLE.</p>
<h3>Indemnification</h3>
<p>If anyone brings a claim against us related to your use of the Site or Apps, your User Content or your violation of these Terms, you agree to indemnify, defend and hold us and our affiliated companies, event providers, suppliers, advertisers and sponsors, and each of our officers, directors, employees, and agents, harmless from and against any and all claims, damages, losses and expenses of any kind (including reasonable legal fees and costs). We reserve the right to take exclusive control and defense of any claim, and you will cooperate fully with us in asserting any available defenses.</p>
<h3>Disputes, Including Mandatory Arbitration and Class Action Waiver</h3>
<p>Any dispute or claim relating in any way to your use of the Site or Apps, or to products or services sold or distributed by us or through us, will be resolved by binding arbitration rather than in court, with the following exceptions:</p>
<ul>
<li>You may assert claims in small claims court if your claims apply;</li>
<li>If a claim involves the conditional license granted to you as described in the Ownership of Content and Grant of Conditional License section above, either of us may file a lawsuit in a federal or state court located within New York County, New York, and we both consent to the jurisdiction of those courts for such purposes; and</li>
<li>In the event that the arbitration agreement in these Terms is for any reason held to be unenforceable, any litigation against us (except for small-claims court actions) may be commenced only in a federal or state court located within New York County, New York, and we both consent to the jurisdiction of those courts for such purposes.</li>
<li>The arbitration agreement in these Terms is governed by the Federal Arbitration Act. It is intended to be broadly interpreted, and will survive termination of these Terms. There is no judge or jury in arbitration, and court review of an arbitration award is limited. However, an arbitrator can award on an individual basis the same damages and relief as a court (including injunctive and declaratory relief or statutory damages), and must follow these Terms as a court would.</li>
<li>To begin an arbitration proceeding, you must send a letter requesting arbitration and describing your claim. You may choose to have the arbitration conducted by telephone, based on written submissions, or in person in the county where you live or at another mutually agreed location.</li>
<li>We each agree that the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding, and that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated or representative action. You agree to waive any right to a jury trial or to participate in a class action. If this specific provision is found to be unenforceable, then the entirety of this arbitration section will be null and void and neither of us will be entitled to arbitrate our dispute.</li>
<li>You agree that these Terms evidence a transaction involving interstate commerce and will be governed by and construed in accordance with federal law to the fullest extent possible.</li>
</ul>
<h3>No Reliance and Forward-Looking Statements</h3>
<p>The information contained on the Site or Apps may not be current and should not be used or relied on for any investment decision regarding our securities or for any similar purpose. If necessary, we will file annual, quarterly and current reports, proxy statements and other information with the United States Securities and Exchange Commission (“SEC”). Copies of our filings are available at the Investor Relations section of this Site or Apps and also at the SEC’s website or Apps at www.sec.gov.</p>
<p>Statements on the Site or Apps regarding our financial condition, results of operations and business and our expectations or beliefs concerning future events that are not historical facts are “Forward-Looking Statements” within the meaning of the Private Securities Litigation Reform Act of 1995. Use of the words “believes,” “expects,” “anticipates,” “plans,” “estimates” or words of similar meaning is intended to identify Forward-Looking Statements but is not the exclusive means of identifying such statements. We caution you that there are some known and unknown factors that could cause actual results to differ materially from any future results, performance or achievements expressed or implied by such ForwardLooking Statements, including but not limited to economic, competitive, governmental and technological factors affecting our operations, markets, products, services and prices, as well as the risks and uncertainties set forth in the documents we file with the SEC, specifically the section titled “Item 1A. Risk Factors” of our most recent Annual Report on Form 10-K and Quarterly Reports on Form 10-Q and Current Reports on Form 8-K. We do not undertake any obligation to publicly update or revise any Forward-Looking Statements because of new information, future events or otherwise.</p>
<h2>Questions</h2>
<p>If you have any questions, comments or complaints regarding these Terms or the Site or Apps, please contact us at:</p>
<p>Broker Genius, Inc.<br/>
<a href="https://support@brokergenius.com/" target="_blank" rel="noopener">support@brokergenius.com</a></p>
		    </div>

            <FormControlLabel
        control={
          <Checkbox checked={accepted} onChange={handleChange} value="checkedA" />
        }
        label="I agree to the terms & conditions and the privacy policy"
      />

        </div>
    )
}